"""init

Revision ID: 814b2124d064
Revises: cdf2bd5bef6b
Create Date: 2025-02-07 21:37:52.960828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '814b2124d064'
down_revision: Union[str, None] = 'cdf2bd5bef6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('published_date', sa.DATE(), autoincrement=False, nullable=False),
                    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('uid', name='books_pkey')
                    )
    op.create_table('users',
                    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('uid', name='users_pkey')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###